---
openapi: 3.0.0
info:
  title: Pack API reference
  description: |
    Pack boxes into containers
  version: 1.0.0
paths:
  /pack:
    post:
      summary: Pack an order
      description: |
        Pack an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PackRequest"
      responses:
        "200":
          description: Pack response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackResponse"

components:
  schemas:
    StackValue:
      type: object
      discriminator:
        propertyName: stackableValueType
        mapping:
          box: "#/components/schemas/BoxStackValue"
          container: "#/components/schemas/ContainerStackValue"      
      properties:
        dx:
          type: integer
        dy:
          type: integer
        dz:
          type: integer
    Stackable:
      type: object
      discriminator:
        propertyName: stackableType
        mapping:
          box: "#/components/schemas/Box"
          container: "#/components/schemas/Container"
      properties:
        id:
          type: string
        description:
          type: string
    ContainerStackValue:
      allOf:
        - $ref: "#/components/schemas/StackValue"
        - type: object    
          properties:
            minLoadWeight:
              type: integer
            maxLoadWeight:
              type: integer
            loadDx:
              type: integer
            loadDy:
              type: integer
            loadDz:
              type: integer
    Container:
      allOf:
        - $ref: "#/components/schemas/Stackable"
        - type: object    
          properties:
            emptyWeight:
              type: integer
            stackableSize:
              $ref: '#/components/schemas/ContainerStackableSize'
            cost:
              type: integer

    ContainerItem:
      allOf:
        - $ref: "#/components/schemas/StackableItem"
        - type: object    
          properties:
            container:
              $ref: '#/components/schemas/Container'        

    BoxStackValue:
       allOf: # Combines the BasicErrorModel and the inline model
        - $ref: "#/components/schemas/StackValue"
        
    Box:
      allOf:
        - $ref: "#/components/schemas/Stackable"
        - type: object    
          properties:
            weight:
              type: integer
            size:
              $ref: '#/components/schemas/BoxStackableSize'

    StackableItem:
      type: object
      discriminator:
        propertyName: stackableType
        mapping:
          box: "#/components/schemas/BoxItem"
          container: "#/components/schemas/ContainerItem"      
      properties:
        count:
          type: integer

    BoxItem:
      allOf:
        - $ref: "#/components/schemas/StackableItem"
        - type: object    
          properties:
            box:
              $ref: '#/components/schemas/Box'

    Surface:
      type: string
      enum:
        - front
        - frontAtZeroDegrees
        - frontAtNinetyDegrees
        - rear
        - rearAtZeroDegrees
        - backAtNinetyDegrees
        - left
        - leftAtZeroDegrees
        - leftAtNinetyDegrees
        - right
        - rightAtZeroDegrees
        - rightAtNinetyDegrees
        - top
        - topAtZeroDegrees
        - topAtNinetyDegrees
        - bottom
        - bottomAtZeroDegrees
        - bottomAtNinetyDegrees
        - all

    StackableSize:
      type: object
      discriminator:
        propertyName: stackableSizeType
        mapping:
          box: "#/components/schemas/BoxStackableSize"
          container: "#/components/schemas/ContainerStackableSize"      
      properties:
        dx:
          type: integer
        dy:
          type: integer
        dz:
          type: integer
        surfaces:
          type: array
          items: 
            $ref: '#/components/schemas/Surface'

    BoxStackableSize:
       allOf:
        - $ref: "#/components/schemas/StackableSize"

    ContainerStackableSize:
       allOf:
        - $ref: "#/components/schemas/StackableSize"
        - type: object    
          properties:
            loadDx:
              type: integer
            loadDy:
              type: integer
            loadDz:
              type: integer
            minLoadWeight:
              type: integer
            maxLoadWeight:
              type: integer

    StackPlacement:
      type: object
      properties:
        stackable:
          $ref: '#/components/schemas/Box'
        stackValue:
          $ref: '#/components/schemas/BoxStackValue'
        x:
          type: integer
        y:
          type: integer
        z:
          type: integer            
    Packager:
      type: object
      properties:
        id:
          type: string
        maxDuration:
          type: integer
    Stack:
      type: object
      properties:
        placements:
          type: array
          items:
            $ref: '#/components/schemas/StackPlacement'

    PackResult:
      type: object
      properties:
        id:
          type: string
        stack:
          $ref: '#/components/schemas/Stack'
        stackValue:
          $ref: '#/components/schemas/ContainerStackValue'

    PackResponse:
      type: object
      properties:
        status:
          type: integer
        results:
          type: array
          items:
            $ref: '#/components/schemas/PackResult'
            
    PackRequest:
      type: object
      properties:
        deadline:
          type: integer
          format: int64
        maxContainers:
          type: integer
        maxDuration:
          type: integer
        containerItems:
          type: array
          items:
            $ref: '#/components/schemas/ContainerItem'
        boxItems:
          type: array
          items:
            $ref: '#/components/schemas/BoxItem'
        packagers:
          type: array
          items:
            $ref: '#/components/schemas/Packager'
